version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hmif-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hmif_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hmif-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 20s
      retries: 10
      interval: 10s

  app:
    build: .
    container_name: hmif-app
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hmif-network
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 15 &&
        echo 'Generating Prisma client...' &&
        npx prisma generate &&
        echo 'Running database migrations...' &&
        npx prisma migrate deploy &&
        echo 'Seeding database...' &&
        npx prisma db seed &&
        echo 'Starting application...' &&
        npm start
      "

networks:
  hmif-network:
    driver: bridge

volumes:
  mysql_data: