version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hmif-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hmif_app
      MYSQL_ROOT_HOST: '%'
    ports:
      - "0.0.0.0:3306:3306"  # Bind ke semua interface
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hmif-network
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: hmif-redis
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"  # Bind ke semua interface
    volumes:
      - redis_data:/data
    networks:
      - hmif-network
    command: redis-server --appendonly yes --bind 0.0.0.0

  app:
    build: .
    container_name: hmif-app
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"  # Bind ke semua interface
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      - DATABASE_URL=mysql://root:rootpassword@mysql:3306/hmif_app
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-here
      - JWT_EXPIRES_IN=1h
      - REFRESH_TOKEN_SECRET=your-refresh-secret-here
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - SESSION_SECRET=your-session-secret-here
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - redis
    networks:
      - hmif-network
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: sh -c "
      npm install && 
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm start
      "

networks:
  hmif-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mysql_data:
  node_modules:
  redis_data: