version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hmif-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hmif_app
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"  # Bind ke semua interface
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hmif-network
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: hmif-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Bind ke semua interface
    networks:
      - hmif-network
    command: redis-server --appendonly yes

  app:
    build: .
    image: node:18-alpine
    container_name: hmif-app
    restart: unless-stopped
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"  # Bind ke semua interface
    environment:
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      - NODE_ENV=production
      - HOST_IP=10.160.132.109
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - redis
    networks:
      - hmif-network
    command: sh -c "
      apk add --no-cache openssl && 
      npm install && 
      npx prisma generate &&
      npm start
      "

networks:
  hmif-network:
    driver: bridge

volumes:
  mysql_data:
  node_modules:
  redis_data: