services:
  mysql:
    image: mysql:8.0
    container_name: hmif-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hmif_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hmif-network
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: hmif-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hmif-network
    command: redis-server --appendonly yes --bind 0.0.0.0

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hmif-app
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"    # HTTP port
      - "3443:3443"    # HTTPS port 
    env_file:
      - .env.docker
    volumes:
      - ./logs:/usr/app/logs
      - ./ssl:/usr/app/ssl  # Mount SSL directory 
    networks:
      - hmif-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  hmif-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  mysql_data:
  redis_data: