services:
  mysql:
    image: mysql:5.7
    container_name: hmif-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hmif_app
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - hmif-network
    command: >
      --bind-address=0.0.0.0 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --max-connections=100
      --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      --general-log=0
      --slow-query-log=0
      --skip-ssl
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword --silent || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: hmif-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hmif-network
    command: redis-server --appendonly yes --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hmif-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3443:3443"
    env_file:
      - .env.docker
    volumes:
      - ./logs:/usr/app/logs
      - ./ssl:/usr/app/ssl
    networks:
      - hmif-network
    environment:
      - DATABASE_URL=mysql://root:rootpassword@mysql:3306/hmif_app?sslmode=disable&ssl=false&allowPublicKeyRetrieval=true
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s

networks:
  hmif-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local